services:
  postgres:
    image: postgres:17
    command: "-d 1"
    volumes:
      - claime_db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=main
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis/redis-stack-server:6.2.6-v6
    ports:
      - "6379:6379"
    volumes:
      - claime_redis:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  upstash-redis-http:
    image: hiett/serverless-redis-http:latest
    ports:
      - "8080:80"
    environment:
      - SRH_MODE=env
      - SRH_TOKEN=local_dev_token
      - SRH_CONNECTION_STRING=redis://redis:6379
    depends_on:
      redis:
        condition: service_healthy

  neon-proxy:
    image: ghcr.io/timowilhelm/local-neon-http-proxy:main
    environment:
      - PG_CONNECTION_STRING=postgres://postgres:postgres@postgres:5432/main
    ports:
      - "4444:4444"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  claime_db:
  claime_redis:
